package day44_Exception;

public class CheckException {
    public static void main(String[] args) {

        System.out.println("Test started");

        // Thread.sleep(3000);

        System.out.println("Completed");


    }

}
